package per.martin.aviation.aircraft.dao;

import java.util.List;
import per.martin.aviation.aircraft.entity.AircraftType ;

public interface AircraftTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer aircraftTypeId) throws RuntimeException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft_type
     *
     * @mbggenerated
     */
    int insert(AircraftType record) throws RuntimeException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft_type
     *
     * @mbggenerated
     */
    AircraftType selectByPrimaryKey(Integer aircraftTypeId) throws RuntimeException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft_type
     *
     * @mbggenerated
     */
    List<AircraftType> selectAll() throws RuntimeException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AircraftType record) throws RuntimeException;
}