package per.martin.aviation.calendar.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user_event_label
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysUserEventLabel {
    /**
     * label_id
     */
    private Integer labelId;

    /**
     * 时间名称
     * name
     */
    private String name;

    /**
     * sys_user
     */
    private Integer sysUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_event_label.label_id
     *
     * @return the value of sys_user_event_label.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_event_label.label_id
     *
     * @param labelId the value for sys_user_event_label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_event_label.name
     *
     * @return the value of sys_user_event_label.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_event_label.name
     *
     * @param name the value for sys_user_event_label.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_event_label.sys_user
     *
     * @return the value of sys_user_event_label.sys_user
     *
     * @mbggenerated
     */
    public Integer getSysUser() {
        return sysUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_event_label.sys_user
     *
     * @param sysUser the value for sys_user_event_label.sys_user
     *
     * @mbggenerated
     */
    public void setSysUser(Integer sysUser) {
        this.sysUser = sysUser;
    }
}