package per.martin.aviation.airport.entity;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table airport
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Airport {
    /**
     * airport_id
     */
    private Integer airportId;

    /**
     * 机场名
     * name
     */
    private String name;

    /**
     * IATA代码
     * IATA
     */
    private String iata;

    /**
     * ICAO代码
     * ICAO
     */
    private String icao;

    /**
     * 飞行区等级1
     * level
     */
    private String level;

    /**
     * level2
     */
    private String level2;

    /**
     * 通航日期
     * navigation_date
     */
    private Date navigationDate;

    /**
     * 机场类型
     * type
     */
    private String type;

    /**
     * 所属地区
     * city
     */
    private String city;

    /**
     * 航站楼面积
     * terminal_area
     */
    private Float terminalArea;

    /**
     * 机位数量
     * number_seat
     */
    private Integer numberSeat;

    /**
     * 运营机构
     * operat_agencies
     */
    private String operatAgencies;

    /**
     * phone1
     */
    private String phone1;

    /**
     * phone2
     */
    private String phone2;

    /**
     * email
     */
    private String email;

    /**
     * website
     */
    private String website;

    /**
     * 航图位置
     */
    private String airChartUrl;

    public String getAirChartUrl() {
        return airChartUrl;
    }

    public void setAirChartUrl(String airChartUrl) {
        this.airChartUrl = airChartUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.airport_id
     *
     * @return the value of airport.airport_id
     *
     * @mbggenerated
     */
    public Integer getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.airport_id
     *
     * @param airportId the value for airport.airport_id
     *
     * @mbggenerated
     */
    public void setAirportId(Integer airportId) {
        this.airportId = airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.name
     *
     * @return the value of airport.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.name
     *
     * @param name the value for airport.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.IATA
     *
     * @return the value of airport.IATA
     *
     * @mbggenerated
     */
    public String getIata() {
        return iata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.IATA
     *
     * @param iata the value for airport.IATA
     *
     * @mbggenerated
     */
    public void setIata(String iata) {
        this.iata = iata == null ? null : iata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.ICAO
     *
     * @return the value of airport.ICAO
     *
     * @mbggenerated
     */
    public String getIcao() {
        return icao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.ICAO
     *
     * @param icao the value for airport.ICAO
     *
     * @mbggenerated
     */
    public void setIcao(String icao) {
        this.icao = icao == null ? null : icao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.level
     *
     * @return the value of airport.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.level
     *
     * @param level the value for airport.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.level2
     *
     * @return the value of airport.level2
     *
     * @mbggenerated
     */
    public String getLevel2() {
        return level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.level2
     *
     * @param level2 the value for airport.level2
     *
     * @mbggenerated
     */
    public void setLevel2(String level2) {
        this.level2 = level2 == null ? null : level2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.navigation_date
     *
     * @return the value of airport.navigation_date
     *
     * @mbggenerated
     */
    public Date getNavigationDate() {
        return navigationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.navigation_date
     *
     * @param navigationDate the value for airport.navigation_date
     *
     * @mbggenerated
     */
    public void setNavigationDate(Date navigationDate) {
        this.navigationDate = navigationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.type
     *
     * @return the value of airport.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.type
     *
     * @param type the value for airport.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.city
     *
     * @return the value of airport.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.city
     *
     * @param city the value for airport.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.terminal_area
     *
     * @return the value of airport.terminal_area
     *
     * @mbggenerated
     */
    public Float getTerminalArea() {
        return terminalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.terminal_area
     *
     * @param terminalArea the value for airport.terminal_area
     *
     * @mbggenerated
     */
    public void setTerminalArea(Float terminalArea) {
        this.terminalArea = terminalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.number_seat
     *
     * @return the value of airport.number_seat
     *
     * @mbggenerated
     */
    public Integer getNumberSeat() {
        return numberSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.number_seat
     *
     * @param numberSeat the value for airport.number_seat
     *
     * @mbggenerated
     */
    public void setNumberSeat(Integer numberSeat) {
        this.numberSeat = numberSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.operat_agencies
     *
     * @return the value of airport.operat_agencies
     *
     * @mbggenerated
     */
    public String getOperatAgencies() {
        return operatAgencies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.operat_agencies
     *
     * @param operatAgencies the value for airport.operat_agencies
     *
     * @mbggenerated
     */
    public void setOperatAgencies(String operatAgencies) {
        this.operatAgencies = operatAgencies == null ? null : operatAgencies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.phone1
     *
     * @return the value of airport.phone1
     *
     * @mbggenerated
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.phone1
     *
     * @param phone1 the value for airport.phone1
     *
     * @mbggenerated
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.phone2
     *
     * @return the value of airport.phone2
     *
     * @mbggenerated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.phone2
     *
     * @param phone2 the value for airport.phone2
     *
     * @mbggenerated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.email
     *
     * @return the value of airport.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.email
     *
     * @param email the value for airport.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airport.website
     *
     * @return the value of airport.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airport.website
     *
     * @param website the value for airport.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }
}