package per.martin.aviation.aircompany.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table air_company
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AirCompany {
    /**
     * air_company_id
     */
    private Integer airCompanyId;

    /**
     * 公司简称
     * short_name
     */
    private String shortName;

    /**
     * 公司名称
     * name
     */
    private String name;

    /**
     * 公司地址
     * address
     */
    private String address;

    /**
     * 公司电话
     * phone_number
     */
    private String phoneNumber;

    /**
     * 公司电话
     * email
     */
    private String email;

    /**
     * 公司网址
     * website
     */
    private String website;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.air_company_id
     *
     * @return the value of air_company.air_company_id
     *
     * @mbggenerated
     */
    public Integer getAirCompanyId() {
        return airCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.air_company_id
     *
     * @param airCompanyId the value for air_company.air_company_id
     *
     * @mbggenerated
     */
    public void setAirCompanyId(Integer airCompanyId) {
        this.airCompanyId = airCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.short_name
     *
     * @return the value of air_company.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.short_name
     *
     * @param shortName the value for air_company.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.name
     *
     * @return the value of air_company.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.name
     *
     * @param name the value for air_company.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.address
     *
     * @return the value of air_company.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.address
     *
     * @param address the value for air_company.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.phone_number
     *
     * @return the value of air_company.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.phone_number
     *
     * @param phoneNumber the value for air_company.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.email
     *
     * @return the value of air_company.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.email
     *
     * @param email the value for air_company.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_company.website
     *
     * @return the value of air_company.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_company.website
     *
     * @param website the value for air_company.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }
}