package per.martin.aviation.airport.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import per.martin.aviation.airport.entity.Airport;

@Repository
public interface AirportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airport
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer airportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airport
     *
     * @mbggenerated
     */
    int insert(Airport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airport
     *
     * @mbggenerated
     */
    Airport selectByPrimaryKey(Integer airportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airport
     *
     * @mbggenerated
     */
    List<Airport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airport
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Airport record);

    /**
     * 单列查询
     */
    Airport selectByColumn(@Param("column") String column,@Param("value") Object value);
}