package per.martin.aviation.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TUserRole {
    /**
     * 用户角色ID
     * user_role_id
     */
    private Integer userRoleId;

    /**
     * 用户ID
     * t_user_id
     */
    private Integer tUserId;

    /**
     * 角色ID
     * role_id
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.user_role_id
     *
     * @return the value of t_user_role.user_role_id
     *
     * @mbggenerated
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.user_role_id
     *
     * @param userRoleId the value for t_user_role.user_role_id
     *
     * @mbggenerated
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.t_user_id
     *
     * @return the value of t_user_role.t_user_id
     *
     * @mbggenerated
     */
    public Integer gettUserId() {
        return tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.t_user_id
     *
     * @param tUserId the value for t_user_role.t_user_id
     *
     * @mbggenerated
     */
    public void settUserId(Integer tUserId) {
        this.tUserId = tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.role_id
     *
     * @return the value of t_user_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.role_id
     *
     * @param roleId the value for t_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}