package per.martin.aviation.aircompany.dao;

import java.util.List;
import per.martin.aviation.aircompany.entity.AirCompany ;

public interface AirCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer airCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_company
     *
     * @mbggenerated
     */
    int insert(AirCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_company
     *
     * @mbggenerated
     */
    AirCompany selectByPrimaryKey(Integer airCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_company
     *
     * @mbggenerated
     */
    List<AirCompany> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AirCompany record);
}