package per.martin.aviation.mapper.authoritymapper;

import org.springframework.stereotype.Repository;
import per.martin.aviation.entity.TUser;
import per.martin.aviation.vo.UserRoleRes;

import java.util.List;

@Repository
public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    TUser insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    TUser selectByPrimaryKey(Integer tuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     */
    List<TUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     */
    int updateByPrimaryKey(TUser record);

    /**
     * 查询用户关联的角色
     */

    List<UserRoleRes> selectUserRole();

}